<p>local Players = game:GetService("Players")<br />local TweenService = game:GetService("TweenService")<br />local player = Players.LocalPlayer<br />local playerGui = player:WaitForChild("PlayerGui")</p>
<p>-- Create ScreenGui<br />local screenGui = Instance.new("ScreenGui")<br />screenGui.Name = "FishingScriptUI"<br />screenGui.ResetOnSpawn = false<br />screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling<br />screenGui.Parent = playerGui</p>
<p>-- Main Frame (Landscape oriented)<br />local mainFrame = Instance.new("Frame")<br />mainFrame.Name = "MainFrame"<br />mainFrame.Size = UDim2.new(0, 750, 0, 400)<br />mainFrame.Position = UDim2.new(0.5, -375, 0.5, -200)<br />mainFrame.BackgroundColor3 = Color3.fromRGB(18, 18, 24)<br />mainFrame.BorderSizePixel = 0<br />mainFrame.Parent = screenGui</p>
<p>-- Add rounded corners<br />local mainCorner = Instance.new("UICorner")<br />mainCorner.CornerRadius = UDim.new(0, 16)<br />mainCorner.Parent = mainFrame</p>
<p>-- Add neon glow effect<br />local mainStroke = Instance.new("UIStroke")<br />mainStroke.Color = Color3.fromRGB(0, 240, 255)<br />mainStroke.Thickness = 3<br />mainStroke.Transparency = 0.3<br />mainStroke.Parent = mainFrame</p>
<p>-- Animated glow effect<br />task.spawn(function()<br /> while mainFrame.Parent do<br /> TweenService:Create(mainStroke, TweenInfo.new(2, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut, -1, true), {<br /> Transparency = 0.6,<br /> Color = Color3.fromRGB(138, 43, 226)<br /> }):Play()<br /> wait(0.1)<br /> end<br />end)</p>
<p>-- Title Bar<br />local titleBar = Instance.new("Frame")<br />titleBar.Name = "TitleBar"<br />titleBar.Size = UDim2.new(1, 0, 0, 60)<br />titleBar.BackgroundColor3 = Color3.fromRGB(12, 12, 18)<br />titleBar.BorderSizePixel = 0<br />titleBar.Parent = mainFrame</p>
<p>local titleCorner = Instance.new("UICorner")<br />titleCorner.CornerRadius = UDim.new(0, 16)<br />titleCorner.Parent = titleBar</p>
<p>-- Accent line under title<br />local accentLine = Instance.new("Frame")<br />accentLine.Size = UDim2.new(1, 0, 0, 2)<br />accentLine.Position = UDim2.new(0, 0, 1, -2)<br />accentLine.BackgroundColor3 = Color3.fromRGB(0, 240, 255)<br />accentLine.BorderSizePixel = 0<br />accentLine.Parent = titleBar</p>
<p>local accentGradient = Instance.new("UIGradient")<br />accentGradient.Color = ColorSequence.new{<br /> ColorSequenceKeypoint.new(0, Color3.fromRGB(138, 43, 226)),<br /> ColorSequenceKeypoint.new(0.5, Color3.fromRGB(0, 240, 255)),<br /> ColorSequenceKeypoint.new(1, Color3.fromRGB(138, 43, 226))<br />}<br />accentGradient.Parent = accentLine</p>
<p>-- Title Text with icon<br />local titleLabel = Instance.new("TextLabel")<br />titleLabel.Size = UDim2.new(1, -80, 1, 0)<br />titleLabel.Position = UDim2.new(0, 20, 0, 0)<br />titleLabel.BackgroundTransparency = 1<br />titleLabel.Text = "🎣 FISHING SCRIPT GENERATOR"<br />titleLabel.TextColor3 = Color3.fromRGB(0, 255, 255)<br />titleLabel.TextSize = 24<br />titleLabel.Font = Enum.Font.GothamBold<br />titleLabel.TextXAlignment = Enum.TextXAlignment.Left<br />titleLabel.Parent = titleBar</p>
<p>-- Version label<br />local versionLabel = Instance.new("TextLabel")<br />versionLabel.Size = UDim2.new(0, 80, 0, 20)<br />versionLabel.Position = UDim2.new(1, -180, 0, 20)<br />versionLabel.BackgroundTransparency = 1<br />versionLabel.Text = "v2.0 PRO"<br />versionLabel.TextColor3 = Color3.fromRGB(138, 43, 226)<br />versionLabel.TextSize = 12<br />versionLabel.Font = Enum.Font.GothamBold<br />versionLabel.Parent = titleBar</p>
<p>-- Credit label<br />local creditLabel = Instance.new("TextLabel")<br />creditLabel.Size = UDim2.new(0, 300, 0, 18)<br />creditLabel.Position = UDim2.new(0, 20, 1, -23)<br />creditLabel.BackgroundTransparency = 1<br />creditLabel.Text = "👨&zwj;💻 This Script Made By DevSnow"<br />creditLabel.TextColor3 = Color3.fromRGB(0, 200, 255)<br />creditLabel.TextSize = 11<br />creditLabel.Font = Enum.Font.GothamMedium<br />creditLabel.TextXAlignment = Enum.TextXAlignment.Left<br />creditLabel.Parent = mainFrame</p>
<p>-- Close Button<br />local closeButton = Instance.new("TextButton")<br />closeButton.Name = "CloseButton"<br />closeButton.Size = UDim2.new(0, 45, 0, 45)<br />closeButton.Position = UDim2.new(1, -55, 0, 7.5)<br />closeButton.BackgroundColor3 = Color3.fromRGB(255, 40, 80)<br />closeButton.Text = "✕"<br />closeButton.TextColor3 = Color3.fromRGB(255, 255, 255)<br />closeButton.TextSize = 22<br />closeButton.Font = Enum.Font.GothamBold<br />closeButton.Parent = titleBar</p>
<p>local closeCorner = Instance.new("UICorner")<br />closeCorner.CornerRadius = UDim.new(0, 10)<br />closeCorner.Parent = closeButton</p>
<p>local closeStroke = Instance.new("UIStroke")<br />closeStroke.Color = Color3.fromRGB(255, 40, 80)<br />closeStroke.Thickness = 2<br />closeStroke.Transparency = 0.5<br />closeStroke.Parent = closeButton</p>
<p>-- Content Frame<br />local contentFrame = Instance.new("Frame")<br />contentFrame.Name = "ContentFrame"<br />contentFrame.Size = UDim2.new(1, -40, 1, -80)<br />contentFrame.Position = UDim2.new(0, 20, 0, 70)<br />contentFrame.BackgroundTransparency = 1<br />contentFrame.Parent = mainFrame</p>
<p>-- Left Panel (Inputs)<br />local leftPanel = Instance.new("Frame")<br />leftPanel.Name = "LeftPanel"<br />leftPanel.Size = UDim2.new(0.55, -10, 1, 0)<br />leftPanel.Position = UDim2.new(0, 0, 0, 0)<br />leftPanel.BackgroundTransparency = 1<br />leftPanel.Parent = contentFrame</p>
<p>-- Right Panel (Actions)<br />local rightPanel = Instance.new("Frame")<br />rightPanel.Name = "RightPanel"<br />rightPanel.Size = UDim2.new(0.45, -10, 1, 0)<br />rightPanel.Position = UDim2.new(0.55, 10, 0, 0)<br />rightPanel.BackgroundColor3 = Color3.fromRGB(24, 24, 32)<br />rightPanel.BorderSizePixel = 0<br />rightPanel.Parent = contentFrame</p>
<p>local rightCorner = Instance.new("UICorner")<br />rightCorner.CornerRadius = UDim.new(0, 12)<br />rightCorner.Parent = rightPanel</p>
<p>local rightStroke = Instance.new("UIStroke")<br />rightStroke.Color = Color3.fromRGB(138, 43, 226)<br />rightStroke.Thickness = 2<br />rightStroke.Transparency = 0.7<br />rightStroke.Parent = rightPanel</p>
<p>-- Function to create modern input field<br />local function createInputField(name, labelText, icon, yPosition, defaultValue, isNumber)<br /> local container = Instance.new("Frame")<br /> container.Name = name .. "Container"<br /> container.Size = UDim2.new(1, 0, 0, 65)<br /> container.Position = UDim2.new(0, 0, 0, yPosition)<br /> container.BackgroundTransparency = 1<br /> container.Parent = leftPanel<br /> <br /> local label = Instance.new("TextLabel")<br /> label.Size = UDim2.new(1, 0, 0, 18)<br /> label.BackgroundTransparency = 1<br /> label.Text = icon .. " " .. labelText<br /> label.TextColor3 = Color3.fromRGB(150, 150, 200)<br /> label.TextSize = 13<br /> label.Font = Enum.Font.GothamMedium<br /> label.TextXAlignment = Enum.TextXAlignment.Left<br /> label.Parent = container<br /> <br /> local inputBox = Instance.new("TextBox")<br /> inputBox.Name = name<br /> inputBox.Size = UDim2.new(1, 0, 0, 38)<br /> inputBox.Position = UDim2.new(0, 0, 0, 22)<br /> inputBox.BackgroundColor3 = Color3.fromRGB(30, 30, 40)<br /> inputBox.BorderSizePixel = 0<br /> inputBox.Text = tostring(defaultValue)<br /> inputBox.TextColor3 = Color3.fromRGB(255, 255, 255)<br /> inputBox.TextSize = 15<br /> inputBox.Font = Enum.Font.Gotham<br /> inputBox.PlaceholderText = "Enter " .. labelText:lower()<br /> inputBox.PlaceholderColor3 = Color3.fromRGB(100, 100, 120)<br /> inputBox.ClearTextOnFocus = false<br /> inputBox.Parent = container<br /> <br /> local inputCorner = Instance.new("UICorner")<br /> inputCorner.CornerRadius = UDim.new(0, 10)<br /> inputCorner.Parent = inputBox<br /> <br /> local inputStroke = Instance.new("UIStroke")<br /> inputStroke.Color = Color3.fromRGB(50, 50, 70)<br /> inputStroke.Thickness = 2<br /> inputStroke.Transparency = 0.5<br /> inputStroke.Parent = inputBox<br /> <br /> -- Add padding<br /> local padding = Instance.new("UIPadding")<br /> padding.PaddingLeft = UDim.new(0, 12)<br /> padding.PaddingRight = UDim.new(0, 12)<br /> padding.Parent = inputBox<br /> <br /> -- Focus effects with neon glow<br /> inputBox.Focused:Connect(function()<br /> TweenService:Create(inputStroke, TweenInfo.new(0.3), {<br /> Transparency = 0, <br /> Color = Color3.fromRGB(0, 240, 255),<br /> Thickness = 3<br /> }):Play()<br /> TweenService:Create(inputBox, TweenInfo.new(0.3), {<br /> BackgroundColor3 = Color3.fromRGB(35, 35, 48)<br /> }):Play()<br /> end)<br /> <br /> inputBox.FocusLost:Connect(function()<br /> TweenService:Create(inputStroke, TweenInfo.new(0.3), {<br /> Transparency = 0.5, <br /> Color = Color3.fromRGB(50, 50, 70),<br /> Thickness = 2<br /> }):Play()<br /> TweenService:Create(inputBox, TweenInfo.new(0.3), {<br /> BackgroundColor3 = Color3.fromRGB(30, 30, 40)<br /> }):Play()<br /> end)<br /> <br /> return inputBox<br />end</p>
<p>-- Create input fields (2x2 grid)<br />local sellPriceInput = createInputField("SellPrice", "Sell Price/KG", "💰", 0, 2, true)<br />local weightInput = createInputField("Weight", "Weight (KG)", "⚖️", 70, 3, true)<br />local fishNameInput = createInputField("FishName", "Fish Name", "🐟", 140, "Northern Pike", false)<br />local fishImageInput = createInputField("FishImage", "Image Asset ID", "🖼️", 210, "rbxassetid://17398142712", false)</p>
<p>-- Tips Container<br />local tipsContainer = Instance.new("Frame")<br />tipsContainer.Size = UDim2.new(1, 0, 0, 50)<br />tipsContainer.Position = UDim2.new(0, 0, 0, 280)<br />tipsContainer.BackgroundColor3 = Color3.fromRGB(255, 180, 0)<br />tipsContainer.BorderSizePixel = 0<br />tipsContainer.Parent = leftPanel</p>
<p>local tipsCorner = Instance.new("UICorner")<br />tipsCorner.CornerRadius = UDim.new(0, 10)<br />tipsCorner.Parent = tipsContainer</p>
<p>local tipsStroke = Instance.new("UIStroke")<br />tipsStroke.Color = Color3.fromRGB(255, 200, 50)<br />tipsStroke.Thickness = 2<br />tipsStroke.Transparency = 0.3<br />tipsStroke.Parent = tipsContainer</p>
<p>local tipsGradient = Instance.new("UIGradient")<br />tipsGradient.Color = ColorSequence.new{<br /> ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 180, 0)),<br /> ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 140, 0))<br />}<br />tipsGradient.Rotation = 45<br />tipsGradient.Parent = tipsContainer</p>
<p>local tipsLabel = Instance.new("TextLabel")<br />tipsLabel.Size = UDim2.new(1, -20, 1, 0)<br />tipsLabel.Position = UDim2.new(0, 10, 0, 0)<br />tipsLabel.BackgroundTransparency = 1<br />tipsLabel.Text = "💡 Tips: You must have the Rod paid with Robux first before using this!"<br />tipsLabel.TextColor3 = Color3.fromRGB(255, 255, 255)<br />tipsLabel.TextSize = 12<br />tipsLabel.Font = Enum.Font.GothamBold<br />tipsLabel.TextWrapped = true<br />tipsLabel.TextXAlignment = Enum.TextXAlignment.Left<br />tipsLabel.TextYAlignment = Enum.TextYAlignment.Center<br />tipsLabel.Parent = tipsContainer</p>
<p>-- Right Panel Content<br />local rightPadding = Instance.new("UIPadding")<br />rightPadding.PaddingTop = UDim.new(0, 15)<br />rightPadding.PaddingBottom = UDim.new(0, 15)<br />rightPadding.PaddingLeft = UDim.new(0, 20)<br />rightPadding.PaddingRight = UDim.new(0, 20)<br />rightPadding.Parent = rightPanel</p>
<p>-- Stats Header<br />local statsHeader = Instance.new("TextLabel")<br />statsHeader.Size = UDim2.new(1, 0, 0, 25)<br />statsHeader.BackgroundTransparency = 1<br />statsHeader.Text = "⚡ QUICK STATS"<br />statsHeader.TextColor3 = Color3.fromRGB(0, 240, 255)<br />statsHeader.TextSize = 16<br />statsHeader.Font = Enum.Font.GothamBold<br />statsHeader.TextXAlignment = Enum.TextXAlignment.Left<br />statsHeader.Parent = rightPanel</p>
<p>-- Total Value Display with glow<br />local totalValueContainer = Instance.new("Frame")<br />totalValueContainer.Size = UDim2.new(1, 0, 0, 55)<br />totalValueContainer.Position = UDim2.new(0, 0, 0, 35)<br />totalValueContainer.BackgroundColor3 = Color3.fromRGB(0, 180, 150)<br />totalValueContainer.BorderSizePixel = 0<br />totalValueContainer.Parent = rightPanel</p>
<p>local totalCorner = Instance.new("UICorner")<br />totalCorner.CornerRadius = UDim.new(0, 12)<br />totalCorner.Parent = totalValueContainer</p>
<p>local totalStroke = Instance.new("UIStroke")<br />totalStroke.Color = Color3.fromRGB(0, 255, 200)<br />totalStroke.Thickness = 2<br />totalStroke.Transparency = 0.3<br />totalStroke.Parent = totalValueContainer</p>
<p>local totalGradient = Instance.new("UIGradient")<br />totalGradient.Color = ColorSequence.new{<br /> ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 180, 150)),<br /> ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 140, 120))<br />}<br />totalGradient.Rotation = 45<br />totalGradient.Parent = totalValueContainer</p>
<p>local totalValueLabel = Instance.new("TextLabel")<br />totalValueLabel.Size = UDim2.new(1, 0, 1, 0)<br />totalValueLabel.BackgroundTransparency = 1<br />totalValueLabel.Text = "💵 Total: $6.00"<br />totalValueLabel.TextColor3 = Color3.fromRGB(255, 255, 255)<br />totalValueLabel.TextSize = 20<br />totalValueLabel.Font = Enum.Font.GothamBold<br />totalValueLabel.Parent = totalValueContainer</p>
<p>-- Execute Button with gradient<br />local executeButton = Instance.new("TextButton")<br />executeButton.Name = "ExecuteButton"<br />executeButton.Size = UDim2.new(1, 0, 0, 55)<br />executeButton.Position = UDim2.new(0, 0, 0, 105)<br />executeButton.BackgroundColor3 = Color3.fromRGB(138, 43, 226)<br />executeButton.Text = "🚀 EXECUTE SCRIPT"<br />executeButton.TextColor3 = Color3.fromRGB(255, 255, 255)<br />executeButton.TextSize = 17<br />executeButton.Font = Enum.Font.GothamBold<br />executeButton.Parent = rightPanel</p>
<p>local executeCorner = Instance.new("UICorner")<br />executeCorner.CornerRadius = UDim.new(0, 12)<br />executeCorner.Parent = executeButton</p>
<p>local executeStroke = Instance.new("UIStroke")<br />executeStroke.Color = Color3.fromRGB(180, 100, 255)<br />executeStroke.Thickness = 2<br />executeStroke.Transparency = 0.3<br />executeStroke.Parent = executeButton</p>
<p>local executeGradient = Instance.new("UIGradient")<br />executeGradient.Color = ColorSequence.new{<br /> ColorSequenceKeypoint.new(0, Color3.fromRGB(138, 43, 226)),<br /> ColorSequenceKeypoint.new(1, Color3.fromRGB(100, 30, 180))<br />}<br />executeGradient.Rotation = 45<br />executeGradient.Parent = executeButton</p>
<p>-- Copy Button<br />local copyButton = Instance.new("TextButton")<br />copyButton.Name = "CopyButton"<br />copyButton.Size = UDim2.new(1, 0, 0, 50)<br />copyButton.Position = UDim2.new(0, 0, 0, 170)<br />copyButton.BackgroundColor3 = Color3.fromRGB(0, 200, 255)<br />copyButton.Text = "📋 COPY TO CLIPBOARD"<br />copyButton.TextColor3 = Color3.fromRGB(255, 255, 255)<br />copyButton.TextSize = 15<br />copyButton.Font = Enum.Font.GothamBold<br />copyButton.Parent = rightPanel</p>
<p>local copyCorner = Instance.new("UICorner")<br />copyCorner.CornerRadius = UDim.new(0, 12)<br />copyCorner.Parent = copyButton</p>
<p>local copyStroke = Instance.new("UIStroke")<br />copyStroke.Color = Color3.fromRGB(100, 220, 255)<br />copyStroke.Thickness = 2<br />copyStroke.Transparency = 0.3<br />copyStroke.Parent = copyButton</p>
<p>local copyGradient = Instance.new("UIGradient")<br />copyGradient.Color = ColorSequence.new{<br /> ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 200, 255)),<br /> ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 150, 200))<br />}<br />copyGradient.Rotation = 45<br />copyGradient.Parent = copyButton</p>
<p>-- Status Label with modern styling<br />local statusLabel = Instance.new("TextLabel")<br />statusLabel.Size = UDim2.new(1, 0, 0, 30)<br />statusLabel.Position = UDim2.new(0, 0, 0, 235)<br />statusLabel.BackgroundTransparency = 1<br />statusLabel.Text = ""<br />statusLabel.TextColor3 = Color3.fromRGB(0, 255, 150)<br />statusLabel.TextSize = 13<br />statusLabel.Font = Enum.Font.GothamMedium<br />statusLabel.Parent = rightPanel</p>
<p>-- Functions<br />local function updateTotalValue()<br /> local sellPrice = tonumber(sellPriceInput.Text) or 0<br /> local weight = tonumber(weightInput.Text) or 0<br /> local total = sellPrice * weight<br /> totalValueLabel.Text = string.format("💵 Total: $%.2f", total)<br /> <br /> -- Animate value change<br /> TweenService:Create(totalValueContainer, TweenInfo.new(0.3), {<br /> Size = UDim2.new(1, 5, 0, 55)<br /> }):Play()<br /> wait(0.1)<br /> TweenService:Create(totalValueContainer, TweenInfo.new(0.3), {<br /> Size = UDim2.new(1, 0, 0, 55)<br /> }):Play()<br />end</p>
<p>local function generateScript()<br /> local sellPrice = tonumber(sellPriceInput.Text) or 2<br /> local weight = tonumber(weightInput.Text) or 3<br /> local fishName = fishNameInput.Text<br /> local fishImage = fishImageInput.Text<br /> <br /> local scriptText = string.format([[<br />local args = {<br /> game:GetService("Players").LocalPlayer:WaitForChild("Backpack"):WaitForChild("Fishing Rod"),<br /> {<br /> Sell_Price_KG = %s,<br /> Fish_Name = "%s",<br /> FishImage = "%s",<br /> Weight = %s<br /> }<br />}</p>
<p>game:GetService("ReplicatedStorage"):WaitForChild("Fishing_System"):WaitForChild("Remotes"):WaitForChild("FinalTask"):FireServer(unpack(args))<br />]], tostring(sellPrice), fishName, fishImage, tostring(weight))<br /> <br /> return scriptText<br />end</p>
<p>local function executeScript()<br /> local sellPrice = tonumber(sellPriceInput.Text) or 2<br /> local weight = tonumber(weightInput.Text) or 3<br /> local fishName = fishNameInput.Text<br /> local fishImage = fishImageInput.Text<br /> <br /> local args = {<br /> game:GetService("Players").LocalPlayer:WaitForChild("Backpack"):WaitForChild("Fishing Rod"),<br /> {<br /> Sell_Price_KG = sellPrice,<br /> Fish_Name = fishName,<br /> FishImage = fishImage,<br /> Weight = weight<br /> }<br /> }<br /> <br /> game:GetService("ReplicatedStorage"):WaitForChild("Fishing_System"):WaitForChild("Remotes"):WaitForChild("FinalTask"):FireServer(unpack(args))<br /> <br /> statusLabel.Text = "✅ Executed!"<br /> statusLabel.TextColor3 = Color3.fromRGB(0, 255, 150)<br /> <br /> wait(3)<br /> statusLabel.Text = ""<br />end</p>
<p>-- Enhanced button animations with glow<br />local function animateButton(button)<br /> button.MouseEnter:Connect(function()<br /> TweenService:Create(button, TweenInfo.new(0.2), {<br /> Size = UDim2.new(button.Size.X.Scale, button.Size.X.Offset + 5, button.Size.Y.Scale, button.Size.Y.Offset + 2)<br /> }):Play()<br /> local stroke = button:FindFirstChildOfClass("UIStroke")<br /> if stroke then<br /> TweenService:Create(stroke, TweenInfo.new(0.2), {Transparency = 0}):Play()<br /> end<br /> end)<br /> <br /> button.MouseLeave:Connect(function()<br /> TweenService:Create(button, TweenInfo.new(0.2), {<br /> Size = UDim2.new(button.Size.X.Scale, button.Size.X.Offset - 5, button.Size.Y.Scale, button.Size.Y.Offset - 2)<br /> }):Play()<br /> local stroke = button:FindFirstChildOfClass("UIStroke")<br /> if stroke then<br /> TweenService:Create(stroke, TweenInfo.new(0.2), {Transparency = 0.3}):Play()<br /> end<br /> end)<br /> <br /> button.MouseButton1Down:Connect(function()<br /> TweenService:Create(button, TweenInfo.new(0.1), {<br /> Size = UDim2.new(button.Size.X.Scale, button.Size.X.Offset - 3, button.Size.Y.Scale, button.Size.Y.Offset - 1)<br /> }):Play()<br /> end)<br /> <br /> button.MouseButton1Up:Connect(function()<br /> TweenService:Create(button, TweenInfo.new(0.1), {<br /> Size = UDim2.new(button.Size.X.Scale, button.Size.X.Offset + 3, button.Size.Y.Scale, button.Size.Y.Offset + 1)<br /> }):Play()<br /> end)<br />end</p>
<p>animateButton(executeButton)<br />animateButton(copyButton)<br />animateButton(closeButton)</p>
<p>-- Event connections<br />sellPriceInput:GetPropertyChangedSignal("Text"):Connect(updateTotalValue)<br />weightInput:GetPropertyChangedSignal("Text"):Connect(updateTotalValue)</p>
<p>executeButton.MouseButton1Click:Connect(function()<br /> executeScript()<br />end)</p>
<p>copyButton.MouseButton1Click:Connect(function()<br /> local script = generateScript()<br /> setclipboard(script)<br /> statusLabel.Text = "📋 Copied!"<br /> statusLabel.TextColor3 = Color3.fromRGB(0, 240, 255)<br /> <br /> wait(3)<br /> statusLabel.Text = ""<br />end)</p>
<p>closeButton.MouseButton1Click:Connect(function()<br /> TweenService:Create(mainFrame, TweenInfo.new(0.3), {<br /> Size = UDim2.new(0, 0, 0, 0)<br /> }):Play()<br /> wait(0.3)<br /> screenGui:Destroy()<br />end)</p>
<p>-- Make draggable<br />local dragging = false<br />local dragInput, mousePos, framePos</p>
<p>titleBar.InputBegan:Connect(function(input)<br /> if input.UserInputType == Enum.UserInputType.MouseButton1 then<br /> dragging = true<br /> mousePos = input.Position<br /> framePos = mainFrame.Position<br /> <br /> input.Changed:Connect(function()<br /> if input.UserInputState == Enum.UserInputState.End then<br /> dragging = false<br /> end<br /> end)<br /> end<br />end)</p>
<p>titleBar.InputChanged:Connect(function(input)<br /> if input.UserInputType == Enum.UserInputType.MouseMovement then<br /> dragInput = input<br /> end<br />end)</p>
<p>game:GetService("UserInputService").InputChanged:Connect(function(input)<br /> if input == dragInput and dragging then<br /> local delta = input.Position - mousePos<br /> mainFrame.Position = UDim2.new(<br /> framePos.X.Scale,<br /> framePos.X.Offset + delta.X,<br /> framePos.Y.Scale,<br /> framePos.Y.Offset + delta.Y<br /> )<br /> end<br />end)</p>
<p>-- Initial setup<br />updateTotalValue()</p>
<p>-- Entrance animation<br />mainFrame.Size = UDim2.new(0, 0, 0, 0)<br />TweenService:Create(mainFrame, TweenInfo.new(0.5, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {<br /> Size = UDim2.new(0, 750, 0, 400)<br />}):Play()</p>
<p>print("🎣 Fishing Script UI (Landscape Dark Theme) loaded successfully!")</p>
